/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import access.Auxiliarfuntion;
import access.clienteDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author brayan
 */
public class vistaCliente extends javax.swing.JFrame {

    /**
     * Creates new form vistaCliente
     */
    public vistaCliente() {
        
        initComponents();
        llenarTabla();
        labelID.setVisible(false);
        textID.setVisible(false);
        jPanel3.setVisible(false);
    }

    public void llenarTabla() {
        clienteDAO dao = new clienteDAO();
 
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            dao.getTable(),
            new String [] {
                "ID", "Documente", "Nombres", "Apellidos", "Telefono"
            }
        )); 
    }
    public void eliminarCampos(){
        textDocumento.setText("");
        textNombres.setText("");
        textApellidos.setText("");
        textTelefono.setText("");
        textID.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        textDocumento = new javax.swing.JTextField();
        textNombres = new javax.swing.JTextField();
        textApellidos = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        radioDelete = new javax.swing.JRadioButton();
        radioUpdate = new javax.swing.JRadioButton();
        radioCreate = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        textID = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(83, 60, 240));

        jPanel2.setBackground(new java.awt.Color(250, 183, 43));

        jLabel5.setBackground(new java.awt.Color(250, 183, 43));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Clientes ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Documento");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Nombres");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Apellidos");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Telefono");

        btn1.setText("Confirmar");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        textDocumento.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textDocumento.setToolTipText("llenar");
        textDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDocumentoActionPerformed(evt);
            }
        });

        textNombres.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textNombres.setToolTipText("llenar");

        textApellidos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textApellidos.setToolTipText("llenar");

        textTelefono.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textTelefono.setToolTipText("llenar");

        buttonGroup1.add(radioDelete);
        radioDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radioDelete.setText("Delete");
        radioDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDeleteActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioUpdate);
        radioUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radioUpdate.setText("Update");
        radioUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUpdateActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioCreate);
        radioCreate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radioCreate.setSelected(true);
        radioCreate.setText("Create");
        radioCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCreateActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        textID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textID.setToolTipText("llenar");
        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });
        textID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textIDKeyTyped(evt);
            }
        });

        labelID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelID.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(labelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioCreate)
                        .addGap(18, 18, 18)
                        .addComponent(radioDelete)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioUpdate)
                        .addGap(0, 94, Short.MAX_VALUE))
                    .addComponent(textApellidos)
                    .addComponent(textTelefono)
                    .addComponent(textNombres)
                    .addComponent(textDocumento))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioDelete)
                    .addComponent(radioUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDocumentoActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
      
          String mensaje = "";
        if (radioCreate.isSelected()){
            mensaje="Creado";
            clienteDAO dao = new clienteDAO();
            Cliente cliente = new Cliente();
            
            String documento = textDocumento.getText();
            String nombres = textNombres.getText();
            String apellidos = textApellidos.getText();
            String telefono = textTelefono.getText();
            
            cliente.setDoc_identidad(Auxiliarfuntion.getIntegerValue(documento));
            cliente.setNombres(nombres);
            cliente.setApellidos(apellidos);
            cliente.setTelefono(Auxiliarfuntion.getIntegerValue(telefono));
            
            boolean respuesta = dao.insertCliente(cliente);
            llenarTabla();
            if(respuesta){
                JOptionPane.showMessageDialog(this , mensaje);
           
            }else{
                mensaje="something was wrong";
                JOptionPane.showMessageDialog(this , mensaje);
            }
            eliminarCampos();
      
        }else if (radioDelete.isSelected()){
            /*            textDocumento.setEditable(false);
            textNombres.setEditable(false);
            textApellidos.setEditable(false);
            textTelefono.setEditable(false);*/
            
            
            clienteDAO dao = new clienteDAO();
            String id_cliente = textID.getText();
            boolean resultado = dao.deleteCliente(id_cliente);
            eliminarCampos();
            
            if (resultado){
                mensaje = "eliminado correctamete";
                JOptionPane.showMessageDialog(this , mensaje);
            }else{
                mensaje = "id no existe";
                JOptionPane.showMessageDialog(this , mensaje);
            }
            llenarTabla();
            
            
            
        }else if(radioUpdate.isSelected()){
            clienteDAO dao = new clienteDAO();
            Cliente cliente = new Cliente();
            
            String documento = textDocumento.getText();
            String nombres = textNombres.getText();
            String apellidos = textApellidos.getText();
            String telefono = textTelefono.getText();
            String id = textID.getText();
            
            cliente.setDoc_identidad(Auxiliarfuntion.getIntegerValue(documento));
            cliente.setNombres(nombres);
            cliente.setApellidos(apellidos);
            cliente.setTelefono(Auxiliarfuntion.getIntegerValue(telefono));
            cliente.setId(Auxiliarfuntion.getIntegerValue(id));
            
            boolean respuesta = dao.updateCliente(cliente);
            
            
            if (respuesta){
                mensaje = "Modificado correctamete";
                JOptionPane.showMessageDialog(this , mensaje);
            }else{
                mensaje = "id no existe";
                JOptionPane.showMessageDialog(this , mensaje);
            }
            eliminarCampos();
            llenarTabla();
            
            
            
        }else{
            //if somethin was wrong
            mensaje = " seleccione alguna opcion";
        }
        
        
        
        
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void radioCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCreateActionPerformed
        // TODO add your handling code here:
        labelID.setVisible(false);
        textID.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_radioCreateActionPerformed

    private void radioDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDeleteActionPerformed
        // TODO add your handling code here:
        labelID.setVisible(true);
        textID.setVisible(true);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_radioDeleteActionPerformed

    private void radioUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUpdateActionPerformed
        // TODO add your handling code here:
        labelID.setVisible(true);
        textID.setVisible(true);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_radioUpdateActionPerformed

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
        String id = textID.getText();
        clienteDAO dao = new clienteDAO();
         
         
        Cliente cliente = dao.getCliente(id);
         
        textDocumento.setText(String.valueOf(cliente.getDoc_identidad()));
        textNombres.setText(cliente.getNombres());
        textApellidos.setText(cliente.getApellidos());
        textTelefono.setText(String.valueOf(cliente.getTelefono()));
         
         
        
    }//GEN-LAST:event_textIDActionPerformed

    private void textIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDKeyPressed

    private void textIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mensaje = "Hasta la Proxima";
        JOptionPane.showMessageDialog(this , mensaje);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btn1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelID;
    private javax.swing.JRadioButton radioCreate;
    private javax.swing.JRadioButton radioDelete;
    private javax.swing.JRadioButton radioUpdate;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textDocumento;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNombres;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
